"""On-disk job store: ``<data_dir>/jobs/<job_id>/job.json`` plus the job's files."""

from __future__ import annotations

import fcntl
import re
import shutil
import threading
from datetime import timedelta
from pathlib import Path
from typing import IO

from pydantic import ValidationError

from vpipe_api.jobs.models import JobRecord, JobStatus, utcnow

_JOB_FILE = "job.json"
_JOB_ID = re.compile(r"job_[0-9A-Z]{26}")


class StoreLockedError(RuntimeError):
    """Another vpipe-api instance is already serving from this data directory."""


class JobStore:
    def __init__(self, data_dir: Path) -> None:
        self._root = data_dir / "jobs"
        self._root.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()
        self._instance_lock: IO[str] | None = None

    def job_dir(self, job_id: str) -> Path:
        # ids are generated by us: anything else (``..``, NUL, huge strings) is unknown
        if _JOB_ID.fullmatch(job_id) is None:
            raise KeyError(job_id)
        return self._root / job_id

    def acquire_instance_lock(self) -> None:
        handle = (self._root.parent / ".lock").open("w")
        try:
            fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError as exc:
            handle.close()
            raise StoreLockedError(
                f"another vpipe-api is already using {self._root.parent}"
            ) from exc
        self._instance_lock = handle

    def release_instance_lock(self) -> None:
        if self._instance_lock is not None:
            fcntl.flock(self._instance_lock, fcntl.LOCK_UN)
            self._instance_lock.close()
            self._instance_lock = None

    def save(self, record: JobRecord) -> JobRecord:
        directory = self.job_dir(record.id)
        directory.mkdir(parents=True, exist_ok=True)
        tmp = directory / f".{_JOB_FILE}.tmp"
        with self._lock:
            tmp.write_text(record.model_dump_json(indent=2), encoding="utf-8")
            tmp.replace(directory / _JOB_FILE)
        return record

    def get(self, job_id: str) -> JobRecord | None:
        try:
            path = self.job_dir(job_id) / _JOB_FILE
        except KeyError:
            return None
        try:
            return JobRecord.model_validate_json(path.read_text(encoding="utf-8"))
        except (FileNotFoundError, ValidationError):
            return None

    def all(self) -> list[JobRecord]:
        records = [self.get(path.name) for path in self._root.iterdir() if path.is_dir()]
        return sorted((r for r in records if r is not None), key=lambda r: r.created_at)

    def delete(self, job_id: str) -> None:
        shutil.rmtree(self.job_dir(job_id), ignore_errors=True)

    def discard_inputs(self, job_id: str, *names: str) -> None:
        """Drop uploaded inputs and intermediates once a job no longer needs them.

        Keeps ``job.json``, the output and ``vpipe.log``; without this, submit-and-cancel
        cycles could fill the disk with decoded images for ``retention_days``.
        """
        directory = self.job_dir(job_id)
        shutil.rmtree(directory / "inputs", ignore_errors=True)
        for name in names:
            (directory / name).unlink(missing_ok=True)

    def recover(self) -> tuple[list[JobRecord], list[JobRecord]]:
        """After a restart: running jobs are lost (fail them); queued jobs can run again.

        Returns ``(requeue, failed)``.
        """
        requeue: list[JobRecord] = []
        failed: list[JobRecord] = []
        for record in self.all():
            if record.status is JobStatus.RUNNING:
                failed.append(
                    self.save(
                        record.failed(
                            "server_restarted",
                            "the server restarted while this job was running",
                            retryable=True,
                        )
                    )
                )
            elif record.status is JobStatus.QUEUED:
                requeue.append(record)
        return requeue, failed

    def prune(self, retention_days: int) -> int:
        """Delete finished jobs (and their outputs) older than the retention window."""
        cutoff = utcnow() - timedelta(days=retention_days)
        removed = 0
        for record in self.all():
            finished = record.finished_at or record.created_at
            if record.status.finished and finished < cutoff:
                self.delete(record.id)
                removed += 1
        return removed
